### 1. Listar todas las tareas
GET http://localhost:3002/api/tareas

### 2. Filtrar tareas pendientes
GET http://localhost:3002/api/tareas?estado=pendiente

### 3. Crear Tarea 1
POST http://localhost:3002/api/tareas
Content-Type: application/json

{
  "nombre": "Estudiar para Programacion IV",
  "estado": "pendiente"
}

### 4. Intentar crear duplicado (Error)
POST http://localhost:3002/api/tareas
Content-Type: application/json

{
  "nombre": "estudiar para programacion iv"
}

### 5. Modificar estado
PUT http://localhost:3002/api/tareas/1
Content-Type: application/json

{
  "nombre": "Estudiar para Programacion IV",
  "estado": "completada"
}

### 6. Eliminar tarea
DELETE http://localhost:3002/api/tareas/1